[package]
name = "dispenser"
version = "0.1.0"

[dependencies.Sui]
local = "../../../sui/crates/sui-framework"

[dependencies.Originmate]
local = "../../../originmate"
# [dependencies.Sui]
# git = "https://github.com/MystenLabs/sui.git"
# subdir = "crates/sui-framework"
# # devnet-0.21.0
# rev = "2d709054a08d904b9229a2472af679f210af3827"

# [dependencies.Originmate]
# git = "https://github.com/Origin-Byte/originmate.git"
# # devnet-0.20.0
# rev = "7dd2b3a6add03d140cdbc48e7c2a0e546ba24047"


[addresses]
nft_protocol = "0x0"
admin = "0x6742b5c18f27719d4281c7564e0d336aa502fea4"
