[package]
name = "dispenser"
version = "1.0.0"
# published_at = "0x0"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
rev = "82c9c80c11488858f1d3930f47ec9f335a566683"
subdir = "crates/sui-framework/packages/sui-framework"
# local = "../../../sui/crates/sui-framework"

[dependencies.NftProtocol]
git = "https://github.com/Origin-Byte/nft-protocol.git"
rev = "47c70bc316292c05678d57f55ff3b3231572f7c4"
# local = "../../../nft-protocol"

[addresses]
dispenser = "0x0"
