[package]
name = "dispenser"
version = "0.1.0"

[dependencies.Sui]
local = "../../../sui/crates/sui-framework"

# a publier, puis inscrire l'adresse de l'objet dans le Move.toml (originmate)
[dependencies.Originmate]
local = "../../../originmate"

[addresses]
nft_protocol = "0x0"
