[package]
name = "dispenser"
version = "1.0.0"
# published_at = "0x0"

[dependencies.Sui]
# git = "https://github.com/MystenLabs/sui.git"
# subdir = "crates/sui-framework/packages/sui-framework"
# testnet-0.30.0
# rev = "de632da6adf673d746155a1624c60a761567c215"
local = "../../../sui/crates/sui-framework/packages/sui-framework"

[dependencies.NftProtocol]
# git = "https://github.com/Origin-Byte/nft-protocol.git"
# rev = "testnet"
local = "../../../nft-protocol"

[addresses]
dispenser = "0x0"
